# Generated by Django 4.1.7 on 2023-02-23 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=30)),
                ('created_at', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
